### PR TITLE
Nightly build crashing on window resize event in macos

### PR DESCRIPTION
**Pull request by bitfriend**
Will fix [issue613](https://github.com/acterglobal/a3/issues/613)

### CODE REVIEW

**Comment by gnunicorn** [comment]
@bitfriend how does this fix the issue? Can we have a link to something describing the problem and put a comment on the line in the code so it doesn't get removed and cause the problem to re-occur in the future!?!

**Review by gnunicorn — APPROVED** [review]
looks fine.

**Comment by gnunicorn** [comment]
thanks!

**Comment by bitfriend** [comment]
2 videos that Emil uploaded was helpful to me.

**Pull request merged**
