### PR TITLE
Fixes for app walkthrough : Add "Next" and "Previous" buttons

### LINKED ISSUE #1643: Fixes for app walkthrough : Add "Next" and "Previous" buttons

### PR DESCRIPTION
**Pull request by kumarpalsinh25**
Fixes, https://github.com/acterglobal/a3/issues/1643

Reference Video:

https://github.com/acterglobal/a3/assets/51526480/c39aefd3-4360-46db-b803-85fc78c928ea

### CODE REVIEW

**Comment by kumarpalsinh25** [comment]
@emilvincentz  
Check video in PR description for the next and previous button support in onboarding info dialogs.

**Comment by emilvincentz** [comment]
awesome! good work @kumarpalsinh25

**Comment by gnunicorn** [comment]
@kumarpalsinh25 I understand _why_ the "skip" jumps but may I make the suggestions to
a) move the `skip` to the top right instead
b) do not use outline buttons but just texts for the `next` and `prev` (the outline is taking a lot of attention, way more than the actual stuff we want the person to focus on)...

**Review by gtalha07 — APPROVED** [review]
Looks good!

**Comment by kumarpalsinh25** [comment]
> @kumarpalsinh25 I understand _why_ the "skip" jumps but may I make the suggestions to a) move the `skip` to the top right instead b) do not use outline buttons but just texts for the `next` and `prev` (the outline is taking a lot of attention, way more than the actual stuff we want the person to focus on)...




https://github.com/acterglobal/a3/assets/51526480/1088110d-d2ef-4c26-9d18-9e5807bbce81

**Comment by gnunicorn** [comment]
:heart: @kumarpalsinh25

**Pull request merged**
