### PR TITLE
Fix bug in early calling of SasVerification::is_done()

### PR DESCRIPTION
**Pull request by bitfriend**
refs https://github.com/acterglobal/a3/issues/1185

### CODE REVIEW

**Comment by bitfriend** [comment]
As Kevin said, we are supposed to use to-device events to verify our other devices, and sync events to verify other users.

**Review by gtalha07 — APPROVED** [review]
LGTM!

**Review by gnunicorn — APPROVED** [review]
but I see at least two more bugs in the initial report this doesn't fix. I'll change the description.

**Comment by bitfriend** [comment]
> but I see at least two more bugs in the initial report this doesn't fix. I'll change the description.

Yeah, it was my bad.

**Pull request merged**
