### PR TITLE
Fixes for space

### PR DESCRIPTION
**Pull request by kumarpalsinh25**
fixes,
 
 - #1603
 - #1654
 - #1644

### CODE REVIEW

**Comment by gtalha07** [comment]
mind sharing screenshot of related spaces UI as of this PR version ?

**Review by gnunicorn — APPROVED** [review]
I'm always a little scared when I see the GridView and sliverdelegates now, since I find them hard to predict for all cases and they have shown several times to be causing runtime problems for specific circumstances (see white page) - which I keep wondering if that isn't something that a type checker should be able to identify ... 

anyways ... _from what I can see_ I do not see any problems here ...

**Comment by kumarpalsinh25** [comment]
> mind sharing screenshot of related spaces UI of this PR version ?


Screenshot 2024-04-19 at 12 36 08 PM

**Comment by kumarpalsinh25** [comment]
> I'm always a little scared when I see the GridView and sliverdelegates now, since I find them hard to predict for all cases and they have shown several times to be causing runtime problems for specific circumstances (see white page) - which I keep wondering if that isn't something that a type checker should be able to identify ...
> 
> anyways ... _from what I can see_ I do not see any problems here ...


Yes, agree with you. I am also afraid `Slivers` comes into the use-case but on the current PR instead of `SliverGrid`, I have used `GridView` and tested code with multiple use-cases and haven't seen any errors so far..

`Slivers` can be useful in certain use-cases but relevant code should be good enough with all the scrolling use-cases.

Hope in future when we refactor `Related-spaces` and `Sub-spaces` code then there might not be any chances of weird errors that we have seen in past.

**Pull request merged**
