### PR TITLE
Fix bug in user search by full name

### PR DESCRIPTION
**Pull request by bitfriend**
- [User search failed](https://github.com/matrix-org/synapse/issues/7588) when namespace contains `.`, for example `miles:acter` works but `miles:acter.global` doesn't work.
- Add integration test for user search

### CODE REVIEW

**Comment by bitfriend** [comment]
Actually rust side is too simple and clear so it can't have bug.
https://github.com/matrix-org/matrix-rust-sdk/blob/e1feefcbb0bed8badec62fe46f59e7a5dd01de60/crates/matrix-sdk/src/client/mod.rs#L387-L408

**Comment by bitfriend** [comment]
SQL query seems to have issue when wildcard contains dot.
https://github.com/matrix-org/synapse/blob/3d87847ecc943c689c4587c5327d744e4a8f92c2/synapse/storage/database.py#L2409

**Comment by bitfriend** [comment]
[This document](https://stackoverflow.com/questions/18636697/sql-like-command-doesnt-work-with-strings-containing-dots) looks helpful.

**Comment by bitfriend** [comment]
> [This document](https://stackoverflow.com/questions/18636697/sql-like-command-doesnt-work-with-strings-containing-dots) looks helpful.

@gnunicorn It proposes regexp instead of wildcard.
Should I change source code of synapse?

**Comment by gnunicorn** [comment]
closing for now.

**Pull request closed without merging**
