### PR TITLE
Limit concurrent HTTP requests

### PR DESCRIPTION
**Pull request by gnunicorn**
1. Upgrades to latest matrix-rust-sdk
2. link to the upgraded [matrix-rust-sdk fork that has support for limiting current http requests](https://github.com/matrix-org/matrix-rust-sdk/pull/3625)
3. set the limits to 100 on desktop, 50 on android and 20 on iOS

Attempt to fix that #1788 errors.

### CODE REVIEW

**Comment by bitfriend** [comment]
Failed when clicking of chat list under reqwest limitation.
This is log.
```
[2024-07-02][22:49:28.105797][acter::api::receipt][INFO] receipt: ReceiptEventContent({"$xHDPrULegcKltaziYo4HrjSHXorte888VfqEFkBOYQc": {"m.read": {"@s7evink:matrix.org": Receipt { ts: Some(2024-07-02T14:49:24.890), thread: Main }}}})
[2024-07-02][22:49:28.106074][acter::api::receipt][INFO] receipt iter: "$xHDPrULegcKltaziYo4HrjSHXorte888VfqEFkBOYQc"
[2024-07-02][22:49:28.106226][acter::api::receipt][INFO] user read receipt: Receipt { ts: Some(2024-07-02T14:49:24.890), thread: Main }
[2024-07-02][22:49:28.113763][acter::api::client::sync][INFO] received sync callback
[2024-07-02][22:49:29.214493][matrix_sdk_crypto::backups][WARN] Trying to backup room keys but no backup key was found
[2024-07-02][22:49:29.215840][acter::api::client::sync][INFO] received sync callback
[2024-07-02][22:49:30.118503][matrix_sdk_crypto::backups][WARN] Trying to backup room keys but no backup key was found
[2024-07-02][22:49:30.119436][acter::api::client::sync][INFO] received sync callback
[2024-07-02][22:49:32.330404][matrix_sdk_crypto::backups][WARN] Trying to backup room keys but no backup key was found
[2024-07-02][22:49:32.331365][acter::api::client::sync][INFO] received sync callback
[2024-07-02][22:49:33.118214][matrix_sdk_crypto::backups][WARN] Trying to backup room keys but no backup key was found
[2024-07-02][22:49:33.118797][acter::api::client::sync][INFO] received sync callback
[2024-07-02][22:49:37.455075][matrix_sdk_crypto::backups][WARN] Trying to backup room keys but no backup key was found
[2024-07-02][22:49:37.455488][acter::api::client::sync][INFO] received sync callback
[2024-07-02][22:49:41.649542][matrix_sdk_crypto::backups][WARN] Trying to backup room keys but no backup key was found
[2024-07-02][22:49:41.649968][acter::api::client::sync][INFO] received sync callback
[2024-07-02][22:49:42.710596][matrix_sdk_crypto::backups][WARN] Trying to backup room keys but no backup key was found
[2024-07-02][22:49:42.711038][acter::api::client::sync][INFO] received sync callback
[2024-07-02][22:49:46.143401][matrix_sdk_crypto::backups][WARN] Trying to backup room keys but no backup key was found
[2024-07-02][22:49:46.143779][acter::api::client::sync][INFO] received sync callback
[2024-07-02][22:49:49.517595][matrix_sdk_crypto::backups][WARN] Trying to backup room keys but no backup key was found
[2024-07-02][22:49:49.518006][acter::api::client::sync][INFO] received sync callback
[2024-07-02][22:49:52.710906][matrix_sdk_crypto::backups][WARN] Trying to backup room keys but no backup key was found
[2024-07-02][22:49:52.711755][acter::api::client::sync][INFO] received sync callback
[2024-07-02][22:49:55.352692][matrix_sdk_crypto::backups][WARN] Trying to backup room keys but no backup key was found
[2024-07-02][22:49:55.352871][acter::api::client::sync][INFO] received sync callback
[2024-07-02][22:49:57.511837][matrix_sdk_crypto::backups][WARN] Trying to backup room keys but no backup key was found
[2024-07-02][22:49:57.512968][acter::api::client::sync][INFO] received sync callback
[2024-07-02][22:49:58.477226][matrix_sdk_crypto::backups][WARN] Trying to backup room keys but no backup key was found
[2024-07-02][22:49:58.477942][acter::api::client::sync][INFO] received sync callback
[2024-07-02][22:50:00.363013][matrix_sdk_crypto::backups][WARN] Trying to backup room keys but no backup key was found
[2024-07-02][22:50:00.363408][acter::api::client::sync][INFO] received sync callback
[2024-07-02][22:50:01.327462][matrix_sdk_crypto::backups][WARN] Trying to backup room keys but no backup key was found
[2024-07-02][22:50:01.327996][acter::api::client::sync][INFO] received sync callback
[2024-07-02][22:50:03.479865][matrix_sdk_crypto::backups][WARN] Trying to backup room keys but no backup key was found
[2024-07-02][22:50:03.480340][acter::api::client::sync][INFO] received sync callback
[2024-07-02][22:50:04.878801][matrix_sdk_crypto::backups][WARN] Trying to backup room keys but no backup key was found
[2024-07-02][22:50:04.879177][acter::api::client::sync][INFO] received sync callback
[2024-07-02][22:50:05.963603][acter::api::client::sync][INFO] received sync callback
[2024-07-02][22:50:05.963386][matrix_sdk_crypto::backups][WARN] Trying to backup room keys but no backup key was found
[2024-07-02][22:50:07.912521][matrix_sdk_crypto::backups][WARN] Trying to backup room keys but no backup key was found
[2024-07-02][22:50:07.912986][acter::api::client::sync][INFO] received sync callback
[2024-07-02][22:50:12.737804][matrix_sdk_crypto::backups][WARN] Trying to backup room keys but no backup key was found
[2024-07-02][22:50:12.738161][acter::api::client::sync][INFO] received sync callback
[2024-07-02][22:50:19.854411][matrix_sdk_crypto::backups][WARN] Trying to backup room keys but no backup key was found
[2024-07-02][22:50:19.854807][acter::api::client::sync][INFO] received sync callback
[2024-07-02][22:50:22.203709][matrix_sdk_crypto::backups][WARN] Trying to backup room keys but no backup key was found
[2024-07-02][22:50:22.204060][acter::api::client::sync][INFO] received sync callback
[2024-07-02][22:50:22.982421][a3::common::room][ERROR] room not found Room not found null 
```

**Comment by gnunicorn** [comment]
@bitfriend pretty sure this doesn't come from this PR ... can you try again since I merged `main` (that contained the fix)...

**Comment by bitfriend** [comment]
> @bitfriend pretty sure this doesn't come from this PR ... can you try again since I merged `main` (that contained the fix)...

But `main` is working fine now.
It doesn't show any error when navigating to chat list page.

**Comment by gnunicorn** [comment]
@bitfriend I pushed an update with a fix. does this still happen to you with it?

**Review by bitfriend — APPROVED** [review]
Nice work in limit of concurrent requests

**Comment by bitfriend** [comment]
On navigation to chat list page, app crash seems to disappear.
Great job.

**Pull request merged**
