### PR TITLE
Fix space navigation crash

### PR DESCRIPTION
**Pull request by bitfriend**
Will fix issue#579.
https://github.com/acterglobal/a3/issues/579
I am sure that space navigation crash comes from nested `ref.watch()`.
Nested `ref.watch()` works in debug build.
But it seems to request big memory in release build.

### CODE REVIEW

**Comment by bitfriend** [comment]
BTW rust sync callback seems to not work on release runtime yet.

**Review by gtalha07 — APPROVED** [review]
LGTM. But it didn't solved crash issue.

**Comment by gnunicorn** [comment]
@bitfriend is this still relevant?

**Comment by bitfriend** [comment]
Main idea of this PR was to replace nested `ref.watch()` with simple `ref.watch()`.
Now `main` branch works well without it, so we can discard this PR.

**Pull request closed without merging**
