### PR TITLE
Several improvements on loading

### LINKED ISSUE #1276: Too many `/devices` requests upon login
With emilio, with a total of `162` session logging in for the first time on a device, issues a whopping `65` distinct requests to `/devices` all with the same result ...

there is something wrong here...

Screenshot 2024-01-15 at 17 15 05

### PR DESCRIPTION
**Pull request by gnunicorn**
Probably best reviewed commit by, as they focus on a specific thing:

- use the `cached_avatar_field` for our own account, https://github.com/acterglobal/a3/commit/b3eff237b18038ca6d92eb6f43226c9d399f0911
  removes a reloading of the _remote_ data of our own avatar whenever it was shown
- Disable Device popups, https://github.com/acterglobal/a3/commit/ffe9d2b1481f151f0376a3e40591ef62b3c4e103
  Removes the `newDevice`-Stream that send kind of pointless popups to the UI and, for every popup it shows, request all the remote devices leading to a lot of requests at startup. Fixes #1276 
- Rust refactorings to simplify the code of:
   - RoomProfile, https://github.com/acterglobal/a3/commit/8b185cd714c9442903208542634cd8d4226464c0
   - UserProfile, https://github.com/acterglobal/a3/commit/41c9fcb4b56014871512fb2dcbd237f0925f5180
- Bump the sync timeout to 25s to make it return before the 30s connection timeout kicks in, https://github.com/acterglobal/a3/commit/0755132d937b331a8d19e144321fd2cbc96ff0a4
- Refactor the way that tasklists are polled and managed to address some issue of #1285 : https://github.com/acterglobal/a3/commit/d8226a29f2eebbba7d9e1a5a4124a37d48f788eb
  The Task itself wasn't a notifier, it now is. Additionally, the `client.taskList`-API is now bound to the `wait_for`-loader to ensure we have this available.
- Replaced the CircularSpinner in several places in the UI with a proper local Skeleton-Loader, cleaning up the entire loading flow and leading to a smoother, less noisy UI, https://github.com/acterglobal/a3/commit/4ac98378e9ce2f120a037d465f3055b885fec8ea

### CODE REVIEW

**Review by kumarpalsinh25 — COMMENTED** [review]
> Refactor the way that tasklists are polled and managed to address some issue of https://github.com/acterglobal/a3/issues/1285 : https://github.com/acterglobal/a3/commit/d8226a29f2eebbba7d9e1a5a4124a37d48f788eb
> The Task itself wasn't a notifier, it now is. Additionally, the client.taskList-API is now bound to the wait_for-loader to ensure we have this available.

I check out your branch and run integration test for Task Module testing. It is getting failed on sign-up process itself.

Screenshot 2024-01-24 at 1 44 57 PM


Error Details:
Screenshot 2024-01-24 at 1 45 40 PM
Screenshot 2024-01-24 at 1 45 52 PM
Screenshot 2024-01-24 at 1 46 10 PM


Side-note: I have run below commands before starting this testing.
- `cargo clean`
- `cargo make android`
- `flutter clean`
- `flutter pub get`

**Comment by kumarpalsinh25** [comment]
@gnunicorn 
Flutter side code related changes looks good to me.

Also I have taken checkout and tested the app. I clearly see the improvements in many places with the cached mechanism however still I'm facing issues on Task module.

Video Reference:
https://github.com/acterglobal/a3/assets/51526480/eb7851a4-1c3a-40e4-a51b-219fc13ea9f6

**Comment by kumarpalsinh25** [comment]
@gnunicorn 
Still with this latest code, some chats avatar is not loading in space chat listing.
Screenshot 2024-01-24 at 6 54 55 PM

**Comment by kumarpalsinh25** [comment]
@gnunicorn 

1) Ah, it was not running that's why faced issue in sign-up. Working now.
> Are you sure the server is up and running.

2) Got you. All good then.
> Yeah, I am not expecting this fixes the tasks feature bugs. It was just a run-by that I came across.

> Not in attempt to fix anything there for good. There very well still be bugs after this PR. In particular only the loading spinner is replaced not the actual loading facility nor any place where it currently says "loading" as a text...

**Review by kumarpalsinh25 — APPROVED** [review]
Great work @gnunicorn. 
Flutter code looks good and I can clearly see big improvements in loading at several modules. 🚀

**Review by gtalha07 — APPROVED** [review]
LGTM! Great work!

**Pull request merged**
